[versions]
agp = "8.13.0"
exomedia = "5.1.0"
kotlin = "2.1.0"
preference = "1.2.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.13.0-beta01" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version = "2.6.1" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version = "2.6.1" }
core = { module = "com.pierfrancescosoffritti.androidyoutubeplayer:core", version = "13.0.0" }
exomedia = { module = "com.devbrackets.android:exomedia", version.ref = "exomedia" }
glide = { module = "com.github.bumptech.glide:glide", version = "5.0.0-rc01" }
junit = { group = "junit", name = "junit", version = "4.13.2" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version = "1.2.0-alpha03" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.6.0-alpha03" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.0-alpha03" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.6.3" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version = "3.0.0-beta-1" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version = "3.0.0-beta-1" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version = "3.0.0-beta-1" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version = "3.0.0-beta-1" }
lottie = { module = "com.airbnb.android:lottie", version = "6.4.0" }
material = { group = "com.google.android.material", name = "material", version = "1.12.0" }
androidx-activity = { group = "androidx.activity", name = "activity", version = "1.9.0-beta01" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.0-alpha13" }
androidx-legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version = "1.0.0" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version = "2.8.0-alpha03" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version = "2.8.0-alpha03" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version = "1.7.0-beta01" }
shimmer = { module = "com.facebook.shimmer:shimmer", version = "0.5.0" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version = "2.6.1" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

